### ISSUE TITLE
filter bug on rorganize.it/groups

### ISSUE THREAD

**Issue by LauresMaures** [rubycorns/rorganize.it#420] opened 2016-01-19 18:32 UTC
Hey,
I found one bug in the group section on rorganize.it
When you search for groups in specific cities/countries and you get the result, the filter doesn't allow you to search for other groups in other places afterwards (-> screenshot below).
![bug_filter_rorganize](https://cloud.githubusercontent.com/assets/16783213/12428159/5923c93a-bee3-11e5-885a-830dd96a8c37.PNG)

**Comment by meikedanst** [comment] 2016-01-19 18:38
very good comment! Maybe you can solve it? :)

**Comment by berlintam** [comment] 2016-01-19 18:48
hey - there's a PR in the works for a reset button which will address this issue (https://github.com/rubycorns/rorganize.it/pull/411). Thanks for commenting!

**Comment by meikedanst** [comment] 2016-01-19 18:55
but wouldn´t it be nice without having to use the reset button?
Why should the list of available options in the filter should get smaller...? :smile:

**Comment by berlintam** [comment] 2016-01-19 18:59
So for example you select Germany & then you can only see the German cities? Would you suggest then that the Country filter should disappear? 

Sounds great if you want to take a crack at it!

**Comment by roschaefer** [comment] 2016-01-19 21:10
![filter_and_scopes](https://cloud.githubusercontent.com/assets/2110676/12431940/8e733ac0-bef8-11e5-8c6b-63a662210786.jpg)

We had a picture similar to this one in our ruby learners group today. If you filter by country or city, the available options in the filter list are the cities/countries of the groups already filtered (black arrow). So the lists will always contain only one element. This probably not the intended behavior. The solution is to get all distinct values of the country column or the city column respectively (blue arrow).

**Comment by til** [comment] 2016-01-20 11:09
I think in general it's a bit weird to have two dropdowns, because it allows to select combinations of country and city that do not fit together. And to come up with a good plan how a selection in one dropdown should limit the choices in the other is tricky (e.g., allow to change country when a city is selected, also clear city?), and probably not worth the effort.

So your change, to always show all options, is the best possible solution imho. Waiting for https://github.com/marjal/rorganize.it/pull/1 to be merged, then we can merge https://github.com/rubycorns/rorganize.it/pull/422.

**Closed** 2016-01-25 18:42 UTC
