### ISSUE TITLE
trying to save a blog post as draft returns 404

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#543] opened 2017-05-02 18:51 UTC
as the title says

**Comment by lislis** [comment] 2017-05-02 18:57
trying to publish a post throws a 502

**Comment by berlintam** [comment] 2017-05-04 14:55
:scream:

**Comment by vsmart** [comment] 2017-05-30 18:20
@lislis do you remember which blog post this was?

**Comment by vsmart** [comment] 2017-05-30 18:35
Couldn't reproduce this, even with the same text + image from @lislis blogpost. Closing the issue.

**Closed** 2017-05-30 18:36 UTC
Labels: bug
