### ISSUE TITLE
Shelly Cloud will shut down on March 31, 2016

### ISSUE THREAD

**Issue by siemieniec** [rubycorns/rorganize.it#392] opened 2015-10-13 10:29 UTC
https://twitter.com/shellycloud/status/653584168077656064
https://shellycloud.com/home

**Comment by lislis** [comment] 2015-10-13 10:40
thanks @siemieniec ! I already got an email from shelly cloud about this.
Can I ask what hoster you'd recommend if we wanted to have servers in the EU?

**Comment by PragTob** [comment] 2015-11-08 15:53
So.. we still haven't figured this one out, have we?

I don't know a hoster that'd host for free, although we could ask anynines as we're sort of friends with them. Otherwise I guess digital ocean would be the most likely option.

**Comment by Malwine** [comment] 2015-11-10 19:37
Ok, we go to Uberspace and we do a offertory to collect money. :moneybag: :moneybag: :moneybag: 
We need 5 Euro per month so 60 Euro per year. 
@til and @BriocheBerlin confirmed.

**Comment by til** [comment] 2015-11-10 19:54
This sounds like a final decision (which I would agree with), but I want to clarify that this is a suggestion reflecting our personal preference - which we hope everyone agrees with of course. Reasons that speak for uberspace are: they are really nice, somehow non-profit, have a lot of packages prepared, and really good documentation (only in german though).

**Comment by lislis** [comment] 2015-11-10 22:39
I like it +1

**Comment by berlintam** [comment] 2015-11-11 08:33
I like it too! ueberspace ie awesome. 

I think also we can just give whatever we want each month, oder? I think 5 is just a suggestion. That being said, I'm fine with 5 :)

ALSO, I just set up jaa with ueberspace & gandi, and I put links to the tutorials here. it was quite painless! https://github.com/rubycorns/jaa/wiki/Hosting-with-uberspage-&-Gandi

**Comment by til** [comment] 2015-11-11 09:21
Thanks for the links to the tutorials Tam!

Yes, 5€ per month is what they wish, and the absolute minimum is 1€/m.
They are very straightforward about it on their
https://uberspace.de/prices page, and also disclose their own costs.
Paying the suggested 5€ would be fair I think, especially since our app
is a rails app, so a bit more heavy on their computing resources than
just a few static html pages.

**Comment by PragTob** [comment] 2015-11-11 10:20
I'm... split about using uberspace. Not having root access (iirc) leaves me scared that we might need a library that they don't have/support. Plus there Postgres is only recent and has fun stuff like ["pay attention to our advise when installing the pg gem"](https://wiki.uberspace.de/database:postgresql#nutzung_mit_ruby) which links to a page where no information about that can be found.

I know they are generally nice et. al., I'm just concerned ;)

**Comment by sareg0** [comment] 2016-01-05 17:58
now that we're all back from holidays, we should probably come to a decision on our migration to another hosting service. Are we sure about uberspace, or were we wanting to investigate other options still?

**Comment by PragTob** [comment] 2016-01-05 18:06
I guess everyone but me is pro uberspace and my good friend @tessi does quite some deploys on uberspace and says it's good to the point where he wrote and maintains [capistrano-uberspace](https://github.com/tessi/capistrano-uberspace) - so I guess that might be worth a try.

**Comment by til** [comment] 2016-01-05 20:25
capistrano-uberspace looks promising. And capistrano 3 is a good choice
for a deployment tool.

Anyone wants to give it a try? Volunteers welcome ;) You could try with
a a newly created uberspace account - the first month on uberspace is
for free and it's quick to create an accout. And then step by step try
to deploy an empty instance of the rorganize.it rails app to it, without
publishing the URL yet. This would allow for risk-less experimentation.

We can (and should) look at it together at the next meetup, but if
someone can prepare something before, that would also be cool.

**Comment by tessi** [comment] 2016-01-05 22:03
I'm also here to help in case you have questions or my capistrano code throws up :)

**Comment by til** [comment] 2016-01-12 21:03
Halfway there, thanks to @madziaf and @BriocheBerlin, following these instructions:

https://wiki.uberspace.de/cool:rails?s[]=rails

http://ror.schedar.uberspace.de/

data needs to be migrated, and some kind of automated deployment set up. Next time.

Ask @madziaf to get ssh access to the server.

**Comment by madziaf** [comment] 2016-01-12 21:07
The app is running demonized. To stop the process, you need to run
```bundle exec thin -a 127.0.0.1 -p 34567 stop```
from the uberspace server.
To start it again:
```bundle exec thin -a 127.0.0.1 -p 34567 -d start```

**Comment by til** [comment] 2016-01-26 18:24
Therefore, the ssh command should be `ssh ror@schedar.uberspace.de`.

**Comment by til** [comment] 2016-01-26 18:29
By the way, did you know that a users' public ssh keys can be seen at github, e.g. mine is here: https://api.github.com/users/til/keys

**Comment by BriocheBerlin** [comment] 2016-01-26 20:49
What we did today:
* added SSH keys
* created a database dump from shellycloud
* created a postgresql db called rorganize_production. you can see it using `psql rorganize_production`, then do `\d`. to quit use `\q`
* changed config/database.yml
* stopped and started app again 

To do:
* only madziaf seems to have the pw...
* pics were not included in the db dump. need to find out how to get them.

Note:
* we tried to create the db NOT using the superuser `ror` but `ror_user`. it didn't work out: `createdb: database creation failed: ERROR:  encoding "SQL_ASCII" does not match locale "en_GB.UTF-8"
DETAIL:  The chosen LC_COLLATE setting requires encoding "UTF8".`
Which seems weird bc that is exactly the combination that the other dbs use.

**Comment by berlintam** [comment] 2016-01-26 20:53
I downloaded a copy of our latest production database by running `shelly backup get` and then copied the file onto the server `scp ~/my-file-path/ourdatabase_file.postgresql.tar ror@schedar.uberspace.de:`

**Comment by til** [comment] 2016-01-27 08:22
Also, you loaded the database dump from shellycloud into the newly
created database on uberspace. For that, the dump file from shellycloud
first needed to be unpacked with tar and gunzip (it's a tar archive that
contains one .gz file, a bit complicated imho), and then loaded with

pg_restore -d ror_production path/to/the/file

As a result, the uberspace app has all the latest data from the live
app, such as people, groups, posts etc., wohoo!

Regarding the uberspace password - I think with ssh access it can always
be recovered using this procedure:
https://uberspace.de/login/pwrecoveryrequest - also it seems we don't
need it for setting up the app, ssh access is sufficient, so no TODO
there.

Right now the new app is down: http://ror.schedar.uberspace.de/ - did
you switch it off on purpose? Just wondering.

**Comment by til** [comment] 2016-01-27 08:32
We should not forget to pay for our uberspace account on time, otherwise
it might get closed.

Payment is due 1 month after creating the account. Who wants to take
responsibility for this (@sareg0 maybe? prettyplease?)? In order to find
out where to pay, someone needs to recover the password to login to the
uberspace dashboard and find out the bank account number and other
payment info.

**Comment by berlintam** [comment] 2016-01-27 08:59
I guess we also need to collect moneyz from everyone to pay for hosting. I feel like we discussed this the other week too. Should we start a rubycorn verein/konto/something?

**Comment by til** [comment] 2016-01-27 09:16
Can't remember what the consensus was last time we discussed it, but my
suggestion would be to start as simple as possible, ie. just collect
some cash next time we meet, and someone needs to step up and transfer
that to the uberspace account.

And maybe start a list of who has given how much.

**Comment by lislis** [comment] 2016-01-27 11:15
I have an uberspace account and can just transfer some :moneybag:

**Comment by lislis** [comment] 2016-01-28 12:11
Maybe to be super clear on this: I have put enough money on the account to keep it running for two months. We should be able to figure something out in the meantime :)

**Comment by til** [comment] 2016-01-28 20:26
Awesome, thanks @lislis :moneybag: :bow:!

**Comment by til** [comment] 2016-02-02 16:48
Regarding the database encoding: I wrote to uberspace support, and they
have now changed the default encoding of new postgresql installations to
UTF8, which is good. We should not see these encoding related errors
anymore. In order to benefit from this, I removed the old installation
(by renaming it to *-old) and ran `uberspace-setup-postgresql` again.

I also created a new `rorganize_production` database (as database user
"ror") and restored the dump file that is still lying around.

So, all should be as before, just better!

If you have made any changes to the postgres config files, those would
need to be carried over, but afaicr there were none necessary.

**Comment by BriocheBerlin** [comment] 2016-02-16 20:13
Today we successfully managed to grab the uploaded pics from shelly:
```
shelly login
shelly file download
```
We then uploaded them to Uberspace via scp (Secure Copy):

`scp -r uploads ror@schedar.uberspace.de:html/rorganize.it/public`

## To Do:
What's left to do now is changing the DNS, looking at you @lislis :stuck_out_tongue:
We'll need you for that I think.
@til found out that time to live currently is 3 hours.

So we'll have to get a new database dump first:
`shelly backup get`
Then log on to Uberspace and drop the database:
```
ssh ror@schedar.uberspace.de
ls
dropdb name_of_database
```
From outside of Uberspace upload new drop:
`scp ~/my-file-path/our_database_file.postgresql.tar ror@schedar.uberspace.de:`

We can think about getting the pics again, we probably don't need to.

Then the DNS needs to be changed.
Today we tried this:
`ping ror.schedar.uberspace.de`  gave us the IP. Then on my local machine on /etc/hosts I made rorganize.it point to the Uberspace IP:
`185.26.156.41   rorganize.it` just to see what happens.

**Comment by lislis** [comment] 2016-02-16 20:58
Should we change dns next Tuesday? I can decrease the time to 5 minutes maybe so we have quicker results.

**Comment by til** [comment] 2016-02-16 21:18
Reducing the ttl to 5 minutes in preparation would be good, yes please!

I can't say whether next Tuesday is a good time, that has to be
ultimately coordinated between you and @briocheberlin - when she has
time to perform the steps outlined above. I can also help remotely if
desired.

**Comment by BriocheBerlin** [comment] 2016-02-22 13:16
@lislis If still fine with you lets do it tomorrow :grin:

**Comment by lislis** [comment] 2016-02-22 13:16
@BriocheBerlin :ok: I'll be at the corns

**Comment by BriocheBerlin** [comment] 2016-02-22 13:32
:smile_cat:

**Comment by berlintam** [comment] 2016-02-22 14:47
SUCH EXCITE!

**Comment by PragTob** [comment] 2016-02-22 16:43
woahhh I haven't done much with that and I'll be the responsible coach if stuff goes wrong. 

I think my throat itches. :P 

See you tomorrow. ;)

**Comment by tessi** [comment] 2016-02-22 16:44
ha! good luck everyone :)

**Comment by sareg0** [comment] 2016-02-22 17:26
hahha!! such exciting!

On Mon, Feb 22, 2016 at 5:44 PM, Philipp Tessenow <notifications@github.com>
wrote:

> ha! good luck everyone :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubycorns/rorganize.it/issues/392#issuecomment-187259059>
> .
>



-- 
Kindest Regards,
Sara
@sareg0 <https://twitter.com/sareg0>

**Comment by BriocheBerlin** [comment] 2016-02-23 19:05
Where is @lislis :frowning:

**Comment by til** [comment] 2016-02-29 14:22
FYI, I got a reminder from Shellycloud that there were still apps
running, so I logged in to https://shellycloud.com/apps/railsgirlsapp
and turned it off.

**Comment by PragTob** [comment] 2016-02-29 14:23
Thanks @til !

**Comment by BriocheBerlin** [comment] 2016-03-01 16:47
Who is getting the Uberspace emails / where are we forwarding them to? Maybe @berlintam or @lislis know?
On every login Uberspace is complaining that we haven't looked at them...

**Comment by berlintam** [comment] 2016-03-01 16:48
I'm not sure.... but they could be going to @madziaf since she was the one who set it up.....

**Comment by lislis** [comment] 2016-03-01 16:50
it's probably going to an internal ror.schedar.uberspace.de address. You need to manually set a redirect. Should I forward it to ror@roganize.it (aka, the mailinglist)?

**Comment by BriocheBerlin** [comment] 2016-03-22 18:35
Ok, we did it! :dancers: (Well, actually several weeks ago...)
Closing this issue now!

**Closed by BriocheBerlin** 2016-03-22 18:35 UTC
