### ISSUE TITLE
Build fails occassionally

### ISSUE THREAD

**Issue by vsmart** [rubycorns/rorganize.it#554] opened 2017-06-06 18:15 UTC
Since the update to Ruby 2.4, the build occasionally fails with the error `click_button: wrong number of arguments`. This seems to be some sort of race condition. Usually restarting the build fixes it :S

**Comment by vsmart** [comment] 2017-06-28 10:06
Update: @til and @sareg0 are also seeing "randomly" failing tests in their PR https://github.com/rubycorns/rorganize.it/pull/528. 🤔 😕

**Comment by sareg0** [comment] 2017-07-04 19:50
I think it's fiiiiixed! BUT @PragTob said that we need to be vigilant about. We can reopen if needed :)

**Comment by til** [comment] 2017-07-04 20:49
Great but how?

**Comment by PragTob** [comment] 2017-07-04 21:32
--> Sara's commits in #528 

Not entirely sure as to WHY (probably some mean meta programming magic) but we noticed that a lot of the `click_link` things that were missing didn't have the entire link text, just part of it. So we made it whole (Like "Ruby Corn" instead of just "Ruby"). Also talked about how we could make it rely more on classes/id and not the text itself.

Also upgraded capybara in hopes that it might include random bugfixes.

Also, we are still using the rack test driver. I was thinking we might wanna switch that to phantomjs/poltergeist. Or might not. Meh.

**Comment by til** [comment] 2017-07-04 21:55
I see. I'll keep my fingers crossed then ;)

I'm sceptic that undeterministic links were the culprit though. I think
that capybara complains when a match is ambiguous and refuses to
proceed.

A nice way to solve ambiguous link matchers can be to use `within` to
narrow the matched area, e.g.

within('nav') do
  click_link 'Ruby Corn'
end

Regarding test driver - I think rack-test is the one to use for all
non-js tests, because it is much faster, and phantomjs/poltergeist
should only be used for js specs (which we don't have yet as far as I
know). I think it's perfectly valid to switch between drivers within a
test suite, based on a :js flag on the spec or something similar.

**Comment by PragTob** [comment] 2017-07-04 22:45
I'm skeptic as well, but it was odd enough that these where the errors we encountered, they all had the same pattern, and they magically went away after fixing them. We even found some issues/stackoverflows that pointed to this error being about ambiguous matches. Idk... maybe there's a difference between `find` and `click_link`... it's just overall weird :)

**Comment by til** [comment] 2017-08-22 21:24
Minor update - @lislis and I saw it today in the wild and could reproduce it by running the specs with the same seed as on a failing Travis build. Now there is an `rspec --bisect` running on Lisa's Laptop - a truly amazing feature by the way - which takes a long time in this case, and hopefully will return with some insights which specs combined cause these failures.

**Comment by lislis** [comment] 2017-08-23 20:43
I just stopped the bisect (after 143 rounds, each taking between 1 and 7 minutes...)
Can't say if the output is useful or not 

> Bisect aborted!
The most minimal reproduction command discovered so far is:
  rspec './spec/controllers/admin_controller_spec.rb[1:1:1,1:1:2,1:2:1]' './spec/controllers/dashboards_controller_spec.rb[1:1:1]' './spec/controllers/groups_controller_spec.rb[1:1:1:1,1:1:1:2,1:1:2:1,1:2:1:1,1:2:1:2,1:2:1:3,1:2:1:4,1:2:2:1,1:2:2:2,1:3:1:1,1:3:1:2,1:3:2:1,1:3:2:2,1:3:2:3]' './spec/controllers/memberships_controller_spec.rb[1:1:1,1:1:2,1:1:3,1:1:4,1:2:1:1,1:2:1:2,1:2:1:3,1:2:2:1,1:2:2:2,1:3:1]' './spec/controllers/people_controller_spec.rb[1:1:1,1:1:2,1:2:1:1,1:2:1:2,1:2:2:1]' './spec/controllers/posts_controller_spec.rb[1:1:1:1,1:1:1:2,1:1:2:1,1:1:3:1,1:2:1:1:1,1:2:1:2:1:1,1:2:1:2:1:2,1:2:1:2:1:3,1:2:1:2:1:4,1:2:1:2:2:1,1:2:1:2:2:2,1:2:1:2:2:3,1:2:1:2:2:4,1:3:1:1:1,1:3:1:1:2,1:3:1:1:3,1:3:1:1:4,1:3:1:2:1,1:3:1:2:2,1:3:1:2:3]' './spec/controllers/registrations_controller_spec.rb[1:1:1,1:1:2,1:1:3]' './spec/features/admin_remove_person_spec.rb[1:1:1,1:2:1,1:2:2]' './spec/features/blog_draft_spec.rb[1:1]' './spec/features/dashboard_spec.rb[1:1:1,1:2:1,1:3:1,1:3:2,1:3:3]' './spec/features/delete_person_spec.rb[1:1:1,1:1:2:1,1:1:2:2,1:1:2:3,1:2:1]' './spec/features/edit_person_spec.rb[1:1:1,1:1:2,1:1:3,1:2:1,1:2:2]' './spec/features/group_create_spec.rb[1:1,1:2]' './spec/features/group_edit_spec.rb[1:1:1,1:1:3,1:2:1,1:3:1]' './spec/features/group_member_spec.rb[1:1,1:2,1:3]' './spec/features/group_topics_spec.rb[1:1,1:2,1:3]' './spec/features/not_logged_in_user_spec.rb[1:1:1,1:2:1,1:3:1,1:4:1,1:5:1,1:6:1]' './spec/features/people_list_spec.rb[1:1]' './spec/features/people_non_public_profile_spec.rb[1:1,2:1]' './spec/features/searching_status_spec.rb[1:1:1,1:2:1]' './spec/features/sign_in_spec.rb[1:1:1,1:1:2,1:2:1,1:2:2,1:3:1,1:4:1]' './spec/features/sign_up_spec.rb[1:1:1]' './spec/features/slug_spec.rb[1:1,1:2]' './spec/features/topics_comments_spec.rb[1:1,1:2]' './spec/features/update_password_spec.rb[1:1]' './spec/features/workshop_coach_spec.rb[1:1]' './spec/helpers/application_helper_spec.rb[1:1,1:2,2:1]' './spec/helpers/groups_helper_spec.rb[1:1:1:1:1,1:1:1:2:1,1:1:2:1,1:2:1:1,1:2:2:1,1:2:2:2,1:3:1,1:3:2]' './spec/helpers/people_helper_spec.rb[1:1:1,1:1:2,1:1:3:1,1:1:4:1,1:2:1,1:2:2:1,1:3:1,1:3:2:1,1:4:1:1,1:4:2:1,1:5:1,1:5:2]' './spec/models/concerns/location_filter_spec.rb[1:1:1:1,1:1:1:2,1:1:1:3,1:2:1,1:2:2]' './spec/models/group_spec.rb[1:1,1:2:1,1:2:2,1:3:1,1:3:2,1:3:3,1:4:1,1:5:1,1:6:1:1,1:6:2:1]' './spec/models/membership_spec.rb[1:1:1:1,1:2:1:1]' './spec/models/null_person_spec.rb[1:1,1:2,1:3]' './spec/models/person_spec.rb[1:1,1:2,1:3,1:4,1:5,1:6,1:7,1:8,1:9:1,1:10:1,1:10:2:1,1:11:1,1:11:2,1:11:3,1:11:4,1:12:1,1:12:2:1,1:12:2:2,1:13:1,1:14:1,1:14:2,1:15:1,1:16:1,1:17:1:1,1:18:1,1:19:1:1,1:19:1:2,1:19:2:1,1:19:2:2,1:20:1:1,1:20:2:1,1:21:1,1:22:1:1,1:22:2:1]' './spec/models/post_spec.rb[1:1:1,1:1:2,1:2:1,1:3:1,1:4,1:5,1:6,1:7:1]' './spec/models/twitter_handle_spec.rb[1:1:1,1:1:2,1:1:3,1:2:1,1:2:2,1:2:3,1:3]' './spec/uploaders/picture_uploader_spec.rb[1:1]' --seed 43364

**Comment by til** [comment] 2017-08-23 22:17
Thanks for waiting so long!

I think this is not really useful, unfortunately. I've seen the same
output today on another project, and decided that bisect wasn't helpful.
There I found the error through other means - it was an indeterminism
that wasn't directly related to the random seed, caused by
autoincrementing ids (id values should never be relied on, but that was
the case there). No idea if that could be the reason in rorganize as
well.

**Comment by til** [comment] 2017-11-29 00:19
Currently there is another occurance on master on Travis. One failure, and it looks like this:

```
  1) Searching for people and location as a group add searching flags via settings
     Failure/Error: click_on 'Edit group'
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./spec/features/searching_status_spec.rb:70:in `go_to_group_settings'
     # ./spec/features/searching_status_spec.rb:33:in `block (3 levels) in <top (required)>'
...
Randomized with seed 15539
```

I couldn't reproduce it locally, even not when running all specs with the same seed. Line 70 is a call to `click_on` (which is an alias in capybara to `click_link_or_button`):

```ruby
  def go_to_group_settings
    click_on 'Edit group'
  end
```

... ❓ ❓ ❓

**Comment by lislis** [comment] 2018-04-18 19:14
This doesn't seem to be happening anymore. Most recent mysterious build failures were related to Travis and not us. 
I'll be optimistic and close this issue, but please reopen it if this reappears.

**Closed by lislis** 2018-04-18 19:14 UTC
